version: '3.8'
services:
  Peer2Profit:
    build:
      context: .
      dockerfile: Dockerfile
    image: enwaiax/peer2profit
    restart: unless-stopped
    environment: 
      - email=jeneuuchan@gmail.com
    command: ["/app/p2pclient", "-l", "$email"]
