version: '3.8'
services:
  per2profit:
    deploy:
      mode: replicated
      replicas: 30
    image: enwaiax/peer2profit
    environment: 
      - email=jeneuuchan@gmail.com
    command: ["/app/p2pclient", "-l", "$email"]
